name       : libkmahjongg
version    : 23.04.2
release    : 46
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.2/src/libkmahjongg-23.04.2.tar.xz : 98e602c7b7b434c7cce697864fd90b8198bbfc1ebb36b44b366e0b20ea50a1a7
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Common code and assets for Kmahjonhgg
description: |
    Library providing common code and assets for Kmahjonhgg.
builddeps  :
    - pkgconfig(Qt5Svg)
    - kcompletion-devel
    - kconfigwidgets-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
