name       : libkmahjongg
version    : 22.08.3
release    : 42
source     :
    - https://cdn.download.kde.org/stable/release-service/22.08.3/src/libkmahjongg-22.08.3.tar.xz : 1ee48f0ebf2deb9f431bd2fb50984ded3085a5fc94aa43ce860ae446ad624b6c
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Common code and assets for Kmahjonhgg
description: |
    Library providing common code and assets for Kmahjonhgg.
builddeps  :
    - pkgconfig(Qt5Svg)
    - kcompletion-devel
    - kconfigwidgets-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
