name       : libkmahjongg
version    : 19.04.0
release    : 2
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.0/src/libkmahjongg-19.04.0.tar.xz : 1ab4461ba92de0cc56bd349a859d5c647f816b20923692237e7f3098ba9dd76e
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Common code and assets for Kmahjonhgg
description: |
    Library providing common code and assets for Kmahjonhgg.
builddeps  :
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules 
    - kcompletion-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
