name       : libkmahjongg
version    : 21.04.0
release    : 27
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.0/src/libkmahjongg-21.04.0.tar.xz : 8b5da3f5fe62ea6ab0f07588b0c5202321a7a2b5c0e1ad319389edbb1bd752d8
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Common code and assets for Kmahjonhgg
description: |
    Library providing common code and assets for Kmahjonhgg.
builddeps  :
    - pkgconfig(Qt5Svg)
    - kcompletion-devel
    - kconfigwidgets-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
