name       : libkmahjongg
version    : 23.04.1
release    : 45
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.1/src/libkmahjongg-23.04.1.tar.xz : bcedcc78f622a37270c5ed41016a3cb41771c9958bbe5cbe6e7c6bbc38d64498
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Common code and assets for Kmahjonhgg
description: |
    Library providing common code and assets for Kmahjonhgg.
builddeps  :
    - pkgconfig(Qt5Svg)
    - kcompletion-devel
    - kconfigwidgets-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
