name       : libkmahjongg
version    : 19.12.0
release    : 10
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.0/src/libkmahjongg-19.12.0.tar.xz : 56e94db922f2b0613721e6ce52ba6dc1825d4a212613b1ff78daed6b9ca95989
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Common code and assets for Kmahjonhgg
description: |
    Library providing common code and assets for Kmahjonhgg.
builddeps  :
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - kcompletion-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
