name       : libkmahjongg
version    : 19.12.1
release    : 11
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.1/src/libkmahjongg-19.12.1.tar.xz : e6a107a32c01c654a2372fda984724b4acd59dbc2902f3f9c7a7d9e14587639c
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Common code and assets for Kmahjonhgg
description: |
    Library providing common code and assets for Kmahjonhgg.
builddeps  :
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - kcompletion-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
