name       : libkmahjongg
version    : 21.12.0
release    : 35
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.0/src/libkmahjongg-21.12.0.tar.xz : 4dbda968e47c35136316037996ded0b648f29539f021785a5f15111bbf96620f
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Common code and assets for Kmahjonhgg
description: |
    Library providing common code and assets for Kmahjonhgg.
builddeps  :
    - pkgconfig(Qt5Svg)
    - kcompletion-devel
    - kconfigwidgets-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
