name       : libkmahjongg
version    : 19.08.3
release    : 9
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.3/src/libkmahjongg-19.08.3.tar.xz : fd7d036ba3b17246fad42e0366003233c42f5b03df881d6bc6886518c2acb165
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Common code and assets for Kmahjonhgg
description: |
    Library providing common code and assets for Kmahjonhgg.
builddeps  :
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - kcompletion-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
