name       : libkmahjongg
version    : 21.08.1
release    : 32
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.1/src/libkmahjongg-21.08.1.tar.xz : 244da128e0ba2fd469fe24b34537186fc10c6cb4c263c18b958cb514c1e7c667
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Common code and assets for Kmahjonhgg
description: |
    Library providing common code and assets for Kmahjonhgg.
builddeps  :
    - pkgconfig(Qt5Svg)
    - kcompletion-devel
    - kconfigwidgets-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
