name       : libkmahjongg
version    : 23.04.3
release    : 47
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.3/src/libkmahjongg-23.04.3.tar.xz : 4331aa00fe4acd8043a0bb0b06c38da14263572423196f4ee7dd174806060ca8
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Common code and assets for Kmahjonhgg
description: |
    Library providing common code and assets for Kmahjonhgg.
builddeps  :
    - pkgconfig(Qt5Svg)
    - kcompletion-devel
    - kconfigwidgets-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
