name       : libkmahjongg
version    : 18.12.2
release    : 1
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.2/src/libkmahjongg-18.12.2.tar.xz : 071ce881b8606e48b8e28fb90a4f063b15bb1a307435603ab4c3bf4f9b07a961
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Common code and assets for Kmahjonhgg
description: |
    Library providing common code and assets for Kmahjonhgg.
builddeps  :
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules 
    - kcompletion-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
