name       : libkmahjongg
version    : 22.04.0
release    : 38
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.0/src/libkmahjongg-22.04.0.tar.xz : 039344f0a490348649054d1777475c55fdb5924d737e1bd34bfc1722f4c4a03c
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Common code and assets for Kmahjonhgg
description: |
    Library providing common code and assets for Kmahjonhgg.
builddeps  :
    - pkgconfig(Qt5Svg)
    - kcompletion-devel
    - kconfigwidgets-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
