name       : libkmahjongg
version    : 20.04.2
release    : 16
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.2/src/libkmahjongg-20.04.2.tar.xz : 9466733c3e0ff8dfcd4eee8bc0467b978ab47e39ded1fe19f7ab9ac263909550
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Common code and assets for Kmahjonhgg
description: |
    Library providing common code and assets for Kmahjonhgg.
builddeps  :
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - kcompletion-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
