name       : libkmahjongg
version    : 20.12.2
release    : 25
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.2/src/libkmahjongg-20.12.2.tar.xz : 5830a157287294dbb2da32920ddcad77e015e551655b442f31212f0f7ad582fa
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Common code and assets for Kmahjonhgg
description: |
    Library providing common code and assets for Kmahjonhgg.
builddeps  :
    - pkgconfig(Qt5Svg)
    - kcompletion-devel
    - kconfigwidgets-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
