name       : libkmahjongg
version    : 20.04.3
release    : 17
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.3/src/libkmahjongg-20.04.3.tar.xz : 24fcff9d91c5143c7275c5c97c2be32e85f5c788749df3acc841fd28bee450a0
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Common code and assets for Kmahjonhgg
description: |
    Library providing common code and assets for Kmahjonhgg.
builddeps  :
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - kcompletion-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
