name       : libkmahjongg
version    : 19.12.2
release    : 12
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.2/src/libkmahjongg-19.12.2.tar.xz : bb76e953fb0b56e95cf290a524a9c66b478e57551b68f37ff049f343aa311233
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Common code and assets for Kmahjonhgg
description: |
    Library providing common code and assets for Kmahjonhgg.
builddeps  :
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - kcompletion-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
