name       : libkmahjongg
version    : 22.04.1
release    : 39
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.1/src/libkmahjongg-22.04.1.tar.xz : ce8de9d665fd72c288dede91488fe390a0123e2b65e50a9e136c1337924d872b
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Common code and assets for Kmahjonhgg
description: |
    Library providing common code and assets for Kmahjonhgg.
builddeps  :
    - pkgconfig(Qt5Svg)
    - kcompletion-devel
    - kconfigwidgets-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
