name       : libkmahjongg
version    : 20.08.3
release    : 21
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.3/src/libkmahjongg-20.08.3.tar.xz : d5da73c85112896d8dfd71847c892436b49a5aa8dfa6b5461545fff577b84b75
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Common code and assets for Kmahjonhgg
description: |
    Library providing common code and assets for Kmahjonhgg.
builddeps  :
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - kcompletion-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
