name       : libkmahjongg
version    : 21.12.1
release    : 36
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.1/src/libkmahjongg-21.12.1.tar.xz : 04f9234443f5185ad0e61ddb41a375bbec4a43f662c30c375755ec1294aba508
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Common code and assets for Kmahjonhgg
description: |
    Library providing common code and assets for Kmahjonhgg.
builddeps  :
    - pkgconfig(Qt5Svg)
    - kcompletion-devel
    - kconfigwidgets-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
