name       : libkmahjongg
version    : 19.04.3
release    : 5
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.3/src/libkmahjongg-19.04.3.tar.xz : 995f10fc62c506dbbb31bdab635fd52cb08e03eb09c859353aaf3423f48c7381
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Common code and assets for Kmahjonhgg
description: |
    Library providing common code and assets for Kmahjonhgg.
builddeps  :
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - kcompletion-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
