name       : libkmahjongg
version    : 21.04.2
release    : 29
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.2/src/libkmahjongg-21.04.2.tar.xz : 02f070f2ad8912814a3a26ee23eaa9a8abf5e22ba2c19c42b2776fe3a6620146
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Common code and assets for Kmahjonhgg
description: |
    Library providing common code and assets for Kmahjonhgg.
builddeps  :
    - pkgconfig(Qt5Svg)
    - kcompletion-devel
    - kconfigwidgets-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
