name       : libkmahjongg
version    : 23.04.0
release    : 44
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.0/src/libkmahjongg-23.04.0.tar.xz : 995b4d8ea15293de092f8dc0257d9f0fbb6c95e65575fb5e826c07516d9ec3fa
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Common code and assets for Kmahjonhgg
description: |
    Library providing common code and assets for Kmahjonhgg.
builddeps  :
    - pkgconfig(Qt5Svg)
    - kcompletion-devel
    - kconfigwidgets-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
