name       : libkmahjongg
version    : 20.12.0
release    : 22
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.0/src/libkmahjongg-20.12.0.tar.xz : d8bd7cf2ac1cf3e5c2616849eaddc513c2a8f45c795ad53c75254e7cdcfa9282
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Common code and assets for Kmahjonhgg
description: |
    Library providing common code and assets for Kmahjonhgg.
builddeps  :
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - kcompletion-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
