name       : libkmahjongg
version    : 21.04.3
release    : 30
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.3/src/libkmahjongg-21.04.3.tar.xz : 8bdf07067fb165b8dbf7d9a652099e0562f65d0376967ea651bb44a4ae0b8552
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Common code and assets for Kmahjonhgg
description: |
    Library providing common code and assets for Kmahjonhgg.
builddeps  :
    - pkgconfig(Qt5Svg)
    - kcompletion-devel
    - kconfigwidgets-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
