name       : libkmahjongg
version    : 21.08.2
release    : 33
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.2/src/libkmahjongg-21.08.2.tar.xz : 6b642c014e4c4d83823d30b3cdda5e22c9794878889e9731e4e24a62df3aaca4
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Common code and assets for Kmahjonhgg
description: |
    Library providing common code and assets for Kmahjonhgg.
builddeps  :
    - pkgconfig(Qt5Svg)
    - kcompletion-devel
    - kconfigwidgets-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
