name       : libkmahjongg
version    : 22.04.3
release    : 41
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.3/src/libkmahjongg-22.04.3.tar.xz : 88db72d067344ee734c2d5113dfa9517538b03ea4e6cfa30a23192f8fc1a22f8
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Common code and assets for Kmahjonhgg
description: |
    Library providing common code and assets for Kmahjonhgg.
builddeps  :
    - pkgconfig(Qt5Svg)
    - kcompletion-devel
    - kconfigwidgets-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
