name       : libkmahjongg
version    : 22.04.2
release    : 40
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.2/src/libkmahjongg-22.04.2.tar.xz : 8421e0180bcf108607e3b4475fc594a84013c9b680d2c3d2aa7745b1b9250e74
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Common code and assets for Kmahjonhgg
description: |
    Library providing common code and assets for Kmahjonhgg.
builddeps  :
    - pkgconfig(Qt5Svg)
    - kcompletion-devel
    - kconfigwidgets-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
