name       : libkmahjongg
version    : 22.12.1
release    : 43
source     :
    - https://cdn.download.kde.org/stable/release-service/22.12.1/src/libkmahjongg-22.12.1.tar.xz : 95afccb9716e8fb5ff0903cf18b22b890bf15bc04c1ba980bd302cc0c08ec4f4
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Common code and assets for Kmahjonhgg
description: |
    Library providing common code and assets for Kmahjonhgg.
builddeps  :
    - pkgconfig(Qt5Svg)
    - kcompletion-devel
    - kconfigwidgets-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
