name       : libkmahjongg
version    : 20.04.0
release    : 14
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.0/src/libkmahjongg-20.04.0.tar.xz : e92a15d81a68260f1dad23a1645d23e5cf5f5e08c9601406b5690b5207361913
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Common code and assets for Kmahjonhgg
description: |
    Library providing common code and assets for Kmahjonhgg.
builddeps  :
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - kcompletion-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
