name       : libkmahjongg
version    : 21.12.3
release    : 37
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.3/src/libkmahjongg-21.12.3.tar.xz : 542d7ef55cb40bb27d2046c364aa0197a88ae4f63e9a546dd39cfe83b18f9b84
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Common code and assets for Kmahjonhgg
description: |
    Library providing common code and assets for Kmahjonhgg.
builddeps  :
    - pkgconfig(Qt5Svg)
    - kcompletion-devel
    - kconfigwidgets-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
