name       : libkmahjongg
version    : 19.08.1
release    : 7
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.1/src/libkmahjongg-19.08.1.tar.xz : c4e3a29bb923ead76f1fb528fa62c677423ebb4ac07dd149a6fc3f6ae055eb39
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Common code and assets for Kmahjonhgg
description: |
    Library providing common code and assets for Kmahjonhgg.
builddeps  :
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - kcompletion-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
