name       : libkmahjongg
version    : 21.08.0
release    : 31
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.0/src/libkmahjongg-21.08.0.tar.xz : 11d6b4396fd86cb2fd4c2445222bb9ef8aa9522afe2d572880016ff7b5eb5ea3
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Common code and assets for Kmahjonhgg
description: |
    Library providing common code and assets for Kmahjonhgg.
builddeps  :
    - pkgconfig(Qt5Svg)
    - kcompletion-devel
    - kconfigwidgets-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
