name       : libkmahjongg
version    : 19.12.3
release    : 13
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.3/src/libkmahjongg-19.12.3.tar.xz : f8ea23952a576e6081052d10e9c967bebe5db017ad62775183f91236158cc19f
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Common code and assets for Kmahjonhgg
description: |
    Library providing common code and assets for Kmahjonhgg.
builddeps  :
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - kcompletion-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
