name       : libkmahjongg
version    : 20.12.1
release    : 23
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.1/src/libkmahjongg-20.12.1.tar.xz : 7dc815fb9b2e893f151be53951a21c2309dde8ceebe3f8ce0ef24d78285b0033
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Common code and assets for Kmahjonhgg
description: |
    Library providing common code and assets for Kmahjonhgg.
builddeps  :
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - kcompletion-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
