name       : libkmahjongg
version    : 21.08.3
release    : 34
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.3/src/libkmahjongg-21.08.3.tar.xz : 6c7695b0f6793b69d607259639a1575066ba8f6c12575c69ce20d11612090666
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Common code and assets for Kmahjonhgg
description: |
    Library providing common code and assets for Kmahjonhgg.
builddeps  :
    - pkgconfig(Qt5Svg)
    - kcompletion-devel
    - kconfigwidgets-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
