name       : libkmahjongg
version    : 21.04.1
release    : 28
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.1/src/libkmahjongg-21.04.1.tar.xz : 5aedad50b112ddec1c98fc3b3a66d85ed40d346ca531c932581e927d133e56be
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Common code and assets for Kmahjonhgg
description: |
    Library providing common code and assets for Kmahjonhgg.
builddeps  :
    - pkgconfig(Qt5Svg)
    - kcompletion-devel
    - kconfigwidgets-devel
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
